# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-28 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicId', models.CharField(max_length=30, unique=True)),
                ('musicName', models.CharField(max_length=30)),
                ('musicTime', models.CharField(max_length=20)),
                ('musicOuther', models.CharField(max_length=30)),
                ('lyricContent', models.TextField()),
                ('musicImg', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='myMusicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=12)),
                ('musicId', models.CharField(max_length=30)),
                ('musicName', models.CharField(max_length=30)),
                ('musicTime', models.CharField(max_length=20)),
                ('musicOuther', models.CharField(max_length=30)),
                ('musicImg', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mymusiclist',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=12, unique=True)),
                ('userName', models.CharField(max_length=20)),
                ('userPwd', models.CharField(max_length=20)),
                ('userImg', models.CharField(max_length=150)),
                ('userToken', models.CharField(max_length=50)),
                ('userRank', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('userobj', django.db.models.manager.Manager()),
            ],
        ),
    ]
