# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=12, unique=True)),
                ('userName', models.CharField(max_length=20)),
                ('userPwd', models.CharField(max_length=20)),
                ('userImg', models.CharField(max_length=150)),
                ('userToken', models.CharField(max_length=50)),
                ('userRank', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
