# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-13 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.CharField(max_length=30, unique=True)),
                ('music_name', models.CharField(max_length=30)),
                ('music_time', models.CharField(max_length=20)),
                ('music_outher', models.CharField(max_length=30)),
                ('lyric_content', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=12, unique=True)),
                ('userName', models.CharField(max_length=20)),
                ('userPwd', models.CharField(max_length=20)),
                ('userImg', models.CharField(max_length=150)),
                ('userToken', models.CharField(max_length=50)),
                ('userRank', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('userobj', django.db.models.manager.Manager()),
            ],
        ),
    ]
