# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-12 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isDelete',
        ),
    ]
