# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-13 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musci',
            old_name='lyric_content',
            new_name='lyricContent',
        ),
        migrations.RenameField(
            model_name='musci',
            old_name='music_id',
            new_name='musicId',
        ),
        migrations.RenameField(
            model_name='musci',
            old_name='music_name',
            new_name='musicName',
        ),
        migrations.RenameField(
            model_name='musci',
            old_name='music_outher',
            new_name='musicOuther',
        ),
        migrations.RenameField(
            model_name='musci',
            old_name='music_time',
            new_name='musicTime',
        ),
    ]
