# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-13 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20190413_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musci',
            name='lyricContent',
            field=models.TextField(),
        ),
    ]
